-- CreateEnum
CREATE TYPE "Role" AS ENUM ('0', '1', '2', '3', '4', '5');

-- CreateEnum
CREATE TYPE "Gender" AS ENUM ('1', '2');

-- CreateEnum
CREATE TYPE "UnitNo" AS ENUM ('1', '2');

-- CreateEnum
CREATE TYPE "Belong" AS ENUM ('1', '4', '8');

-- CreateEnum
CREATE TYPE "EmpStatus" AS ENUM ('0', '1', '2', '9');

-- CreateEnum
CREATE TYPE "Reachability" AS ENUM ('1', '2');

-- CreateEnum
CREATE TYPE "Progress" AS ENUM ('1', '2', '3');

-- CreateEnum
CREATE TYPE "PhysicalCondition" AS ENUM ('1', '2', '3');

-- CreateEnum
CREATE TYPE "Relationship" AS ENUM ('1', '2', '3');

-- CreateTable
CREATE TABLE "DEPARTMENT_MST" (
    "DEPARTMENT_ID" CHAR(1) NOT NULL,
    "DEPARTMENT_NAME" VARCHAR(20) NOT NULL,

    CONSTRAINT "DEPARTMENT_MST_pkey" PRIMARY KEY ("DEPARTMENT_ID")
);

-- CreateTable
CREATE TABLE "TEAM_MST" (
    "TEAM_ID" CHAR(5) NOT NULL,
    "TEAM_NAME" VARCHAR(50) NOT NULL,
    "UNIT_NO" CHAR(1) NOT NULL,

    CONSTRAINT "TEAM_MST_pkey" PRIMARY KEY ("TEAM_ID")
);

-- CreateTable
CREATE TABLE "EMPLOYEE_MST" (
    "EMP_ID" VARCHAR(10) NOT NULL,
    "DEPARTMENT_ID" CHAR(1) NOT NULL,
    "TEAM_ID" CHAR(5),
    "EMP_NO" CHAR(4),
    "ROLE" CHAR(1) NOT NULL DEFAULT '0',
    "EMP_LNAME" VARCHAR(10) NOT NULL,
    "EMP_FNAME" VARCHAR(10) NOT NULL,
    "EMP_LNAME_KANA" VARCHAR(20) NOT NULL,
    "EMP_FNAME_KANA" VARCHAR(20) NOT NULL,
    "GENDER" CHAR(1) NOT NULL,
    "BIRTHDAY" DATE,
    "START_DATE" DATE,
    "BELONG" CHAR(1) NOT NULL,
    "EMP_STATUS" CHAR(1) NOT NULL DEFAULT '0',
    "CHANGE_DATE" DATE,
    "MAIL_ADDRESS" VARCHAR(100),

    CONSTRAINT "EMPLOYEE_MST_pkey" PRIMARY KEY ("EMP_ID")
);

-- CreateTable
CREATE TABLE "LOGIN" (
    "EMP_ID" VARCHAR(10) NOT NULL,
    "LOGIN_ID" VARCHAR(20) NOT NULL,
    "PASSWORD" VARCHAR(20) NOT NULL,

    CONSTRAINT "LOGIN_pkey" PRIMARY KEY ("EMP_ID")
);

-- CreateTable
CREATE TABLE "WEEKLY_REPORT" (
    "WEEKLY_REPORT_ID" SERIAL NOT NULL,
    "EMP_ID" VARCHAR(10) NOT NULL,
    "LEADER_EMP_ID" VARCHAR(10) NOT NULL,
    "USER_COMPANY_NAME" VARCHAR(100),
    "PRIME_CONTRACTOR_NAME" VARCHAR(100),
    "ONSITE_ADDRESS" VARCHAR(200) NOT NULL,
    "FIXED_TIME" VARCHAR(100) NOT NULL,
    "SALES_EMP_ID" VARCHAR(10) NOT NULL,
    "PERIOD_START_DATE" DATE NOT NULL,
    "PERIOD_END_DATE" DATE NOT NULL,
    "SOURCE_OF_SALES_INFO" VARCHAR(100),
    "HOW_TO_COLLECT_SALES_INFO" VARCHAR(100),
    "SALES_INFO" TEXT,
    "AVG_OVERTIME" VARCHAR(10) NOT NULL,
    "WORK_CONTENT" VARCHAR(100) NOT NULL,
    "MINIMUN_WORK_TIME" DECIMAL(3,0) NOT NULL,
    "REACHABILITY" CHAR(1) NOT NULL,
    "PROGRESS" CHAR(1) NOT NULL,
    "PHYSICAL_CONDITION" CHAR(1) NOT NULL,
    "RELATIONSHIP" CHAR(1) NOT NULL,
    "FAILURE_POINTED_OUT" TEXT,
    "IMPRESSION" TEXT NOT NULL,
    "DIFFICULTY_LEVEL" DECIMAL(3,0),
    "SENCE_OF_SCHEDULE" DECIMAL(3,0),
    "SITUATION_OF_OTHER_EMPLOYEES" TEXT,

    CONSTRAINT "WEEKLY_REPORT_pkey" PRIMARY KEY ("WEEKLY_REPORT_ID")
);

-- AddForeignKey
ALTER TABLE "EMPLOYEE_MST" ADD CONSTRAINT "EMPLOYEE_MST_DEPARTMENT_ID_fkey" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENT_MST"("DEPARTMENT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE_MST" ADD CONSTRAINT "EMPLOYEE_MST_TEAM_ID_fkey" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM_MST"("TEAM_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LOGIN" ADD CONSTRAINT "LOGIN_EMP_ID_fkey" FOREIGN KEY ("EMP_ID") REFERENCES "EMPLOYEE_MST"("EMP_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WEEKLY_REPORT" ADD CONSTRAINT "WEEKLY_REPORT_EMP_ID_fkey" FOREIGN KEY ("EMP_ID") REFERENCES "EMPLOYEE_MST"("EMP_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WEEKLY_REPORT" ADD CONSTRAINT "WEEKLY_REPORT_LEADER_EMP_ID_fkey" FOREIGN KEY ("LEADER_EMP_ID") REFERENCES "EMPLOYEE_MST"("EMP_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WEEKLY_REPORT" ADD CONSTRAINT "WEEKLY_REPORT_SALES_EMP_ID_fkey" FOREIGN KEY ("SALES_EMP_ID") REFERENCES "EMPLOYEE_MST"("EMP_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
